language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAJDQQB67DVKQ2S6LQ
  secret_access_key:
    secure: Ygtpu8O1JRd2uZJS8m5aW4PUJTbTQzBcHCfOt4Ob/ULvA6KzRIFGmu+KYOUTBm2dHSRfY7a/WXYDljeRPwlQs/LYQ9CTSyENpySUSCP3JdehWPS8Pwkm/42XmYb6WPuI9amMXL6sfqBplM8xeDyVT2VQRcX+LmKkz8qcyxZWHh+KL5HihNKbB4wT1PQBbC0MEh00YZA1Q+CFkkknp8EqZQIobWnUsqgjQE9Rg9uOMBTAN8T3EQnoWj+zibXgFzUq1G+oRRLY1RWlIv0b3bkLFfWHUNTxLdrLdK5uD8NXQQ+3/jlbrpK08ugeOGJMn3j/Q+vL3QD9wdGA0GEU/T7g0UotiDs6DhuZMdu5Mb4SFru6psNYe/WJWG2tRGvvQPvbaSE0x9GpsqTlqWew2t3X3S9HXZ/YITxJtRV7hxVn7BFXUNX3fUN1nvCsJ8xjp0LPKfkdRh+B8Ceo8xPhKyEYGJPhB+Z9LrTHZ7CXl0DBNwLoYTpApd4KYWfnOwscnVPbHV5HmZhxUAs2gZgAc1aPkB5BJJz2tLeCV/wYjFHkJYCCWjv0o6+14Qmm36pbJfWoD+uP08lGR+1Ed4pDllUWu6zxD71/DgG+yUV5LxdCvC/OYB6zWmM4hKhGJd1isaQGjlCdI0Z8TpP8P51opiEahf1n4aRJGuRGiwXEhh45LwI=
  bucket: lauragonzalez-cc
  local-dir: public
  acl: public_read
  on:
    repo: walaura/watermelon-pizza
