language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAIEPKMCGHFTWD76AA
  secret_access_key: 
    secure: "FjZNGVnvhfsNcUFL5I+ALduOcfCab3k1tNzckPz1dAo40/nNOMS0B2nIGpQpq1Hfh+z4Fl5jYhQN0VA2ScXmdI/uSUyRAeDeDo2R4SZeQYA2Z2kFHHD+XHQIbwHQNSGcDZxUrAhvO/l6MizUUagNQegOK7UBeznPrsy/NuVXmQkdEx0RXL1yTGHms8UzwOOf+tbU4AeIUFL70E3zuE0o38AhTuqQ1MdOS588u8sSoL2HaC8cMKYWLvmRpyC2GDkeoI+eYhw6AxRCc6iDB4iHY7/KKtRm0m2v8ZC1Vr6unjF+6UYLJHi/6lqBkBeGWiJCm6746nT3qqF8Ml5zvaR4g5ePHsevwRFF4ntyOddFQ/RsV1gKqTKGNORuhRCIAjCs6GDKbBefG5kb1Ct964hBiVmldbFX93zcxV5gnnNkBh02SMr3B6/IBrjtGAkRqGEV3e1B60Frn+DmjNnrfhWNccx2sIWE/O79lBi7Y5fI+Yfpe5BVTHhd1XGXoLkRFewfhwAe9/Y2hwW2vKpWb29162ZPgrB2LBpdAdpDtYxhnTqIl7Y9X5m9SWLaX0mCX2zQUkqWrhyGOfZQF2UvNcOCcmujYYcJwyNKsq77GIEgxxDkYwGesoLLA0gV7rIbe4eygbW/iQz0Pcq/cul6DUw7ZyejQYiJdbKiQXQyGxJq0es="
  bucket: lauragonzalez-cc
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: walaura/watermelon-pizza
