language: node_js
node_js:
- node
sudo: false
install:
- npm install -g travis-ci-cloudfront-invalidation
- npm install
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: lauragonzalez-cc
  skip-cleanup: true
  local-dir: out
  acl: public_read
  on:
    branch: master
    repo: walaura/watermelon-pizza
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
