language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAIEPKMCGHFTWD76AA
  secret_access_key: 
    secure: "g+vWgsP7ca+G4rTZ7zMx6F0HMYO9mtk14uISpeuJQP0GsJAeTelRTbqk6ttH/G52Zw0DBkmrZ8e2AtwC+tZibO1ACVffl0/VcC94+QYBUlVnTSUFcJ7iArU92G/5Wwn9DXdKvq0JHYfym4IT/oShtyLIwbseCjSvWeA9t6080WwFyVQPG0qoaq5mXb+siau22Mb+RdzmJnBJRz7Sr8wJ2W5QObNSXZwKTW5TeV4I03cWbheLN5f/uBXNx0pXa06SIp1WiB7o09Q5kkEZf/e7yPO5wJp9MMr2gMXRI2lRQ4n/+FOV3saCAbuHQCenOQK2c+6NcEhT6tSnt6WXVht8xvJzgp9PbIGsVnVIUmOa9vdvmJPbH+cFv/r7HKUWojuabv80xmPaNfMuInYhevEuxXswQMzliJoOAaHc9SXp9hpXp6HNBFXOni4qkvLXlblLssxveYpSmWwJ0kICduN01/zDIWTjaublIfDt9iZEh6IthN1qYpwT+y/hvgawPaXXxUVQw3EuiB/EysAat7ZAHRPzlMFK750onJoM9vJtqk6c+t0M/2dNYKr8c7n3gaCl9sZSo5337trkOZU/XD1FignUXNg4caNUUStbfazLs+3C4KcPzy/RyAiurGwXLa5RNeIPMmDjlppNgSNdnt2zyjesVRN+AWmwPJgEJ/o+Zkc="
  bucket: lauragonzalez-cc
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: walaura/watermelon-pizza
