language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAIEPKMCGHFTWD76AA
  secret_access_key: 
    secure: "W3rDKIL8UD4QfuALGYct4c784vF6wAVpqWYgSnsQgwL/zldyVlKbLM2NJA3vrH3GvL6f5fLlmhgyLeLcp/+l9epwyHYXcb9f3dOXHDrUfPunVf/AocAgn7WigfYMcv+aFBN1bT6ij2WmPSslAqN22qiZPRsmD71ay/xYvngQq7nZFEN9tz+wvhAreQCzQ6C0Y09c0yFkm2ykprbZ9iUYUlaXgGwbGY3ziHiLEe/G6ZX9kFUIQ0VmnAiqWOoCXTehpYF6c/X2ngC+BhkYe6ZKYkMmFU6Q8iq/h9YCMaUw23tnKh6hm9CbJXnk92/ruDUMdSTXsCB6TuBU2Ji85XpO9pnUOCLGqnJsjEdG1DYf3dAJ+y+0pMwaZjCd7gO2jnIqqOl45jT2FT8AN51qVNcxHB7AIQTPJ76baMCRcrHbuTshKvZDDnjdxNVOMlr1fx9c8hgBg/FqdvPNBNZ9at/M9l+79PSk6i0KATBbF/8L/q65vSjAY4Gwwtq3yVqlKuZSE8DyxT+a2xV+fv/rl+sInqixnU/VXFTo3kufFUHJM+cKOOfgk1neMirgpXizxJmQ3qinP+C/ADj9p5a49X2hu/lLp9DTnE5y0q+HT3xhk2iPIR1RCD4Ak9al6sJdbz0TXQizXCwVbrB58yE8X/c9m2Z3IeqXhoewIkAWiMgzjh8="
  bucket: lauragonzalez-cc
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: walaura/watermelon-pizza
