language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAIEPKMCGHFTWD76AA
  secret_access_key:
    secure: 2ftTOsmZUdDVmcRX6a1yvx7SuJzsJEe7Qj/1IqWWurJyfb0ect1ORAqhG/vd9uRDmUshtKJwwPoM4UBeVfAY5h0SbA7wXD0oyOvSg5ihYcCamobARONjrOC8DTv63LZJa1eQZKbpn/q3SK8qDF3WAm3PZI8627XuEwCC2PvtB0QQDkHhyHhlcw//QpbYmTPXk+YxbrRKTm7K8TQUL3yZvU9H3fHiExkkEeVUtW4fuzLBck5YUijB/WUHJreksjbBhpziHF8oFdh/0pvhLaYP7maITK/qBdfTWnIvc8IV9gxJOWqHEN9jokJbZMnxcVNFwNIHETQiNFmcl7jMH2NWFH+rQIOkV/WEPr3WObqbI23y4RIfNUFwzTorf5McnR6aSpOgQsA32LrytAvo/nW9RtO7aL+SR49eF3gop0nKuc4AHC+oRCwB5mbrjoMqrT9JhXYqMUVUBm10QFETSTe4G9oLRDb3O+YUItGItlh6dsOGE7CJO9sjxmAdzQ2YTZUOGqMi54d48pP8OpEbLZZB8K1eNALZeWb48LcXjlUK0VZ8fB7RrdsX/6E4/6Nul/lPdgbwO58Jl2HG6SvZcQIqRlbkUZpvz2WH/MLcuhqJ92YADjiicKCLNvVOcdab/Sr6nwiN0k2WlBTF9O9iiDFlMBxcjRTlL9d6E8eiuIA6tm4=
  bucket: lauragonzalez-cc
  local-dir: public
  acl: public_read
  on:
    repo: walaura/watermelon-pizza
