language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAJEK57L5ZTOYIED3A
  secret_access_key: secure: "CVqhPEDg4dWM7TKjqkZ3CalOby+C2jGNNBQ6MUQsm8DNmHmKCiLMDD1IwxCC5D9rl7xzGUqijQNqaEyylLWjgybVFkpqghJa40TZUVK8SGfsR6xVSeREG/2SqeBc88ytZchVS55v0JUmAL/56KqQKqacwSax4sGw5PZSalvXetO4NYhibcSKzxXffIyil41IYWngku96gXFECc1lVcLKEhvHcWAVSrvATrlEzRMWbJkZ6BXEQs6F9zRIzKNrcrhxjTdNUACYFpKXkVbS++7+WwRE0DU7vBOpvQAhs0+BfnYzZkhqwDwqSJESC4MCLtGXHyQSXfePQSzXsVrVFECSoJr3vvik4zIHf2TXCGIkAIxmdtVoa5MAbrwWa4+zSZStxCngpJARd4/D8eyaovaY6ny+bkPaQkf+GpQZQwISoDFsNmtg9r8XXHn0P2Lpc2OBQu/JTgAFw1DKxo4IKhK0cco5C9N6ipZsiclt30xugzkX391c5+1R5rw+kI/m3SY6K94lV1u/0PHBElM6+nnci3rX0yBUuRNOSM9gU9wQXJTAcuYRaH8016SHnavjKHYonJd3IZRX+mY1D8kXmOp4OyAel/W4Dhgg98oNjvs42GywkwOhuuutxaZZYuPG3dy0fzYgkQNFlxJAxn8wqVxLP7hoLx5lKopoaE3J48UNXMk="
  bucket: lauragonzalez-cc
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: walaura/watermelon-pizza
