language: node_js
node_js:
- node
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAJH5KJ3PCX7QUHSCQ
  secret_access_key: "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"
  bucket: lauragonzalez-cc
  skip-cleanup: true
  local-dir: public
  acl: public_read
  on:
    branch: master
    repo: walaura/watermelon-pizza
